spring:
  application:
    name: keycloak
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers_skip_column_definitions: 'true'
        globally_quoted_identifiers: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/keycloak
    password: postgres
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-keycloak-realm

server:
  port: 8090